# Problem 3:

An artist competition has entries from three painters: Pam, Paul and Peter.

- Pam put in 15 paintings, 4% of her works have won First Prize.
- Paul put in 5 paintings, 5% of his works have won First Prize.
- Peter put in 10 paintings, 3% of his works have won First Prize.

What is the probability that Pam will win First Prize?

## Using Python with Synthetic Data

In [ ]:
# Import needed modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from fractions import Fraction

### Choose size of population

In [ ]:
n = 30_000
f"{n:,}"

'30,000'

### Empty data frame

In [ ]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

### Create the population, i.e. the number of paintings

In [ ]:
df["id"] = np.arange(n)
df[:5]

   id
0   0
1   1
2   2
3   3
4   4

In [ ]:
df.shape

(30000, 1)

### Tag with the owner of the painting

In [ ]:
df["owner"] = np.repeat("Pam Paul Peter".split(), [15_000, 5_000, 10_000])
df

          id  owner
0          0    Pam
1          1    Pam
2          2    Pam
3          3    Pam
4          4    Pam
...      ...    ...
29995  29995  Peter
29996  29996  Peter
29997  29997  Peter
29998  29998  Peter
29999  29999  Peter

[30000 rows x 2 columns]

In [ ]:
df[["owner"]].value_counts(normalize=True).sort_index()*100

owner
Pam      50.000000
Paul     16.666667
Peter    33.333333
Name: proportion, dtype: float64

In [ ]:
df[["owner"]].value_counts().sort_index()

owner
Pam      15000
Paul      5000
Peter    10000
Name: count, dtype: int64

### Tag those that won first prize

In [ ]:
# set everyone to "show"
df["prize"] = "show"
df[:5]

   id owner prize
0   0   Pam  show
1   1   Pam  show
2   2   Pam  show
3   3   Pam  show
4   4   Pam  show

In [ ]:
df[["owner","prize"]].value_counts().sort_index()

owner  prize
Pam    show     15000
Paul   show      5000
Peter  show     10000
Name: count, dtype: int64

In [ ]:
# adjust 4% of Pam's to "first"
who = ( df["owner"] == "Pam" )
who_first = df[ who ].sample(frac=0.04).index
df.loc[ who_first, "prize" ] = "first"
# df.iloc[ who_first, df.columns.get_loc("prize") ] = "first"
df[["owner","prize"]].value_counts().sort_index()

owner  prize
Pam    first      600
       show     14400
Paul   show      5000
Peter  show     10000
Name: count, dtype: int64

In [ ]:
# adjust 5% of Paul's to "first"
who = ( df["owner"] == "Paul" )
who_first = df[ who ].sample(frac=0.05).index
df.loc[ who_first, "prize" ] = "first"
# df.iloc[ who_first, df.columns.get_loc("prize") ] = "first"
df[["owner","prize"]].value_counts().sort_index()

owner  prize
Pam    first      600
       show     14400
Paul   first      250
       show      4750
Peter  show     10000
Name: count, dtype: int64

In [ ]:
# adjust 3% of Peter's to "first"
who = ( df["owner"] == "Peter" )
who_first = df[ who ].sample(frac=0.03).index
df.loc[ who_first, "prize" ] = "first"
# df.iloc[ who_first, df.columns.get_loc("prize") ] = "first"
df[["owner","prize"]].value_counts().sort_index()

owner  prize
Pam    first      600
       show     14400
Paul   first      250
       show      4750
Peter  first      300
       show      9700
Name: count, dtype: int64

In [ ]:
vc_ds = df[["owner","prize"]].value_counts().sort_index()
vc_ds

owner  prize
Pam    first      600
       show     14400
Paul   first      250
       show      4750
Peter  first      300
       show      9700
Name: count, dtype: int64

In [ ]:
firsts = vc_ds[:,"first"]
firsts

owner
Pam      600
Paul     250
Peter    300
Name: count, dtype: int64

In [ ]:
firsts/firsts.sum() * 100

owner
Pam      52.173913
Paul     21.739130
Peter    26.086957
Name: count, dtype: float64