# Problem 2

Beth is planning a picnic today, but the morning is cloudy.

- 50% of all rainy days start off cloudy
- Cloudy mornings are common (40% of all days start cloudy)
- This is usually a dry month (10% of days tend to be rainy)

What is the chance of rain during the day when it starts of cloudy?

## Using Python with Synthetic Data

In [ ]:
# Import needed modules
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from fractions import Fraction

### Choose size of population

In [ ]:
n = 1_000
f"{n:,}"

'1,000'

### Empty data frame

In [ ]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

### Create the population, i.e. the number of days

In [ ]:
df["id"] = np.arange(n)
df[:5]

   id
0   0
1   1
2   2
3   3
4   4

In [ ]:
df.shape

(1000, 1)

### Tag with the rainy days

In [ ]:
df["rainy"] = np.repeat("yes no".split(), [100,900])
df

      id rainy
0      0   yes
1      1   yes
2      2   yes
3      3   yes
4      4   yes
..   ...   ...
995  995    no
996  996    no
997  997    no
998  998    no
999  999    no

[1000 rows x 2 columns]

In [ ]:
df[["rainy"]].value_counts(normalize=True).sort_index()*100

rainy
no       90.0
yes      10.0
Name: proportion, dtype: float64

In [ ]:
df[["rainy"]].value_counts().sort_index()

rainy
no       900
yes      100
Name: count, dtype: int64

### Tag cloudy days

In [ ]:
# set cloudy to "no"
df["cloudy"] = "no"
df[:5]

   id rainy cloudy
0   0   yes     no
1   1   yes     no
2   2   yes     no
3   3   yes     no
4   4   yes     no

In [ ]:
df[["rainy","cloudy"]].value_counts().sort_index()

rainy  cloudy
no     no        900
yes    no        100
Name: count, dtype: int64

In [ ]:
# adjust 50% of rainy days to cloudy "yes"
days = ( df["rainy"] == "yes" )
days_rainy = df[ days ].sample(frac=0.50).index
df.loc[ days_rainy, "cloudy" ] = "yes"
# df.iloc[ days_rainy, df.columns.get_loc("cloudy") ] = "yes"
df[["rainy","cloudy"]].value_counts().sort_index()

rainy  cloudy
no     no        900
yes    no         50
       yes        50
Name: count, dtype: int64

In [ ]:
# adjust remainder of not rainy days to cloudy "yes"
days = ( df["rainy"] == "no" )
days_rainy = df[ days ].sample(n=(400-50)).index
df.loc[ days_rainy, "cloudy" ] = "yes"
# df.iloc[ days_rainy, df.columns.get_loc("cloudy") ] = "yes"
df[["rainy","cloudy"]].value_counts().sort_index()

rainy  cloudy
no     no        550
       yes       350
yes    no         50
       yes        50
Name: count, dtype: int64

In [ ]:
vc_ds = df[["rainy","cloudy"]].value_counts().sort_index()
vc_ds

rainy  cloudy
no     no        550
       yes       350
yes    no         50
       yes        50
Name: count, dtype: int64

In [ ]:
rainy = vc_ds[:,"yes"]
rainy

rainy
no     350
yes     50
Name: count, dtype: int64

In [ ]:
rainy/rainy.sum() * 100

rainy
no     87.5
yes    12.5
Name: count, dtype: float64